#python research_agent.py
from datetime import datetime
from pathlib import Path
from textwrap import dedent

from agno.agent import Agent
from agno.models.openai import OpenAIChat
from agno.tools.exa import ExaTools

import os
from dotenv import load_dotenv 
load_dotenv()

os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY")
os.environ["EXA_API_KEY"] = os.getenv("EXA_API_KEY")

today = datetime.now().strftime("%Y-%m-%d")

agent = Agent(
    model=OpenAIChat(id="gpt-4o"),
    tools=[ExaTools(start_published_date=today, type="keyword")],
    description=dedent("""\
        You are a Research Scientist Ravi Chandra Vedula, a distinguished Ocean research scientist working on Ocean Observations with expertise
        in analyzing and synthesizing multi dimensional ocean parameters from Slocum Gliders. Your specialty lies in creating
        compelling, fact-based scientific reports that combine academic rigor with engaging narrative for scientific and technical audience in your niche.

        Your writing style is:
        - Clear and authoritative
        - Engaging but professional
        - Fact-focused with proper citations
        - Critical and insightful pertaining to subject
        - Accessible to educated as well as non-specialists\
    """),
    instructions=dedent("""\
        Begin by running 3 distinct searches to gather comprehensive information.
        Analyze and cross-reference sources for accuracy and relevance.
        Structure your report following professional standards of scientific publications like{JGR | Scientific Reports | Nature Communications} but maintain readability.
        Include only verifiable facts with proper citations.
        Create an engaging narrative that guides the reader through complex topics.
        Include All citations and references following {APA} style
        End with actionable takeaways and future research scope.\
    """),
    expected_output=dedent("""\
    
    ---
    Report generated by Dr Ravi Chandra Vedula
    Ocean Observations Network, ODICT, INCOIS, Hyderabad.
    Date: {current_date}\
    """),
    markdown=True,
    show_tool_calls=True,
    add_datetime_to_instructions=True,
)

# Example usage
if __name__ == "__main__":
    # Generate a research report on a cutting-edge topic
    agent.print_response(
        "Research the latest developments in AUV and Ocean Gliders Operations in Indian Ocean", stream=True
    )

# More example prompts to try:
"""
Try these research topics:
1. "Analyze the current state of solid-state batteries"
2. "Research recent breakthroughs in CRISPR gene editing"
3. "Investigate the development of autonomous vehicles"
4. "Explore advances in quantum machine learning"
5. "Study the impact of artificial intelligence on healthcare"
"""